export const TUNING = {
  population: 30,
  idleRadius: 65,
  idleSpeed: 0.65,
  required: 12,
  finishWindow: 5,
  walkSpeed: 2.6,
  airSpeed: 5.2,
  jumpSpeed: 11,
  gravity: 1500,
  platformSpeed: 64,
  platformTravel: 96,
  areaSpacing: 20000,
  pipeCooldown: 0.8,
  npcGapSpeed: 6.8,
  springImpulse: 17,
  swimImpulse: 4.5,
  swimGravity: 0.25,
  swimFallSpeed: 3,
  deathSequenceSeconds: 2.8,
  warningRange: 185,
  hearingRange: 440,
  warningCooldown: 1.3,
  warningSound: 0.35,
  bubbleTime: 2.1,
  fasterAt: 30,
  fireballsAt: 60,
  firstMarioAt: 5,
  marioSight: 520,
  marioChaseSeconds: 6,
  marioReaction: 0.25,
  marioCrowdLimit: 5,
  marioCrowdRange: 800,
  marioCrowdSpeedBonus: 2,
  starSeconds: 10,
  giantScale: 3,
  marioStunSeconds: 2,
  marioDefeatSeconds: 3,
  playerFireCooldown: 1,
  playerFireballScale: 3,
  blockBounceSeconds: 0.22,
  pipeWidth: 64,
  pipeHeight: 64,
  brickSize: 32,
  groundY: 430,
} as const;

export const PHRASES = [
  "Run! Mario is coming!",
  "Move! The plumber is coming!",
  "Run! The demon is coming!",
  "Run! The mustache is coming!",
  "Get out! The red hat is coming!",
  "Run for the goal! Mario is close!",
  "Keep moving! Mario is on his way!",
  "Flee! Those boots are coming!",
  "Scramble! The plumber is almost here!",
  "Run your shells off! Mario is coming!",
  "Run! Trouble has a mustache, and it's coming!",
  "Get to safety! Mario is coming!",
];

export const MAP_TOP = TUNING.groundY - 13 * 32;
