// Generated by scripts/extract-levels.mjs. Bundled JSON; no runtime fetch.
import area00 from "./area-00.json" with { type: "json" };
import area01 from "./area-01.json" with { type: "json" };
import area02 from "./area-02.json" with { type: "json" };
import area20 from "./area-20.json" with { type: "json" };
import area21 from "./area-21.json" with { type: "json" };
import area22 from "./area-22.json" with { type: "json" };
import area23 from "./area-23.json" with { type: "json" };
import area24 from "./area-24.json" with { type: "json" };
import area25 from "./area-25.json" with { type: "json" };
import area26 from "./area-26.json" with { type: "json" };
import area27 from "./area-27.json" with { type: "json" };
import area28 from "./area-28.json" with { type: "json" };
import area29 from "./area-29.json" with { type: "json" };
import area2a from "./area-2a.json" with { type: "json" };
import area2b from "./area-2b.json" with { type: "json" };
import area2c from "./area-2c.json" with { type: "json" };
import area2d from "./area-2d.json" with { type: "json" };
import area2e from "./area-2e.json" with { type: "json" };
import area2f from "./area-2f.json" with { type: "json" };
import area30 from "./area-30.json" with { type: "json" };
import area31 from "./area-31.json" with { type: "json" };
import area32 from "./area-32.json" with { type: "json" };
import area33 from "./area-33.json" with { type: "json" };
import area34 from "./area-34.json" with { type: "json" };
import area35 from "./area-35.json" with { type: "json" };
import area40 from "./area-40.json" with { type: "json" };
import area41 from "./area-41.json" with { type: "json" };
import area42 from "./area-42.json" with { type: "json" };
import area60 from "./area-60.json" with { type: "json" };
import area61 from "./area-61.json" with { type: "json" };
import area62 from "./area-62.json" with { type: "json" };
import area63 from "./area-63.json" with { type: "json" };
import area64 from "./area-64.json" with { type: "json" };
import area65 from "./area-65.json" with { type: "json" };
export const AREAS = {
  "00": area00,
  "01": area01,
  "02": area02,
  "20": area20,
  "21": area21,
  "22": area22,
  "23": area23,
  "24": area24,
  "25": area25,
  "26": area26,
  "27": area27,
  "28": area28,
  "29": area29,
  "2a": area2a,
  "2b": area2b,
  "2c": area2c,
  "2d": area2d,
  "2e": area2e,
  "2f": area2f,
  "30": area30,
  "31": area31,
  "32": area32,
  "33": area33,
  "34": area34,
  "35": area35,
  "40": area40,
  "41": area41,
  "42": area42,
  "60": area60,
  "61": area61,
  "62": area62,
  "63": area63,
  "64": area64,
  "65": area65,
};
